# This is a special configuration file to run tests on Travis-CI via
# GitHub notifications when changes are committed.
#
# For technical details, see http://travis-ci.org/

language: python
cache: pip
jobs:
  include:
    - stage: test
      python: "2.7"
    - stage: test
      python: "3.6"

before_install:
 - "if grep '\t' *.py *.rst; then echo 'Tabs are bad, please use four spaces.'; false; fi"
 - "if grep -n -r '[[:blank:]]$' *.py *.rst; then echo 'Please remove trailing whitespace.'; false; fi"
 - pip install --upgrade pip setuptools
 - pip install flake8 flake8-docstrings restructuredtext-lint
 - echo "Using flake8 to check Python code"
 - restructuredtext-lint *.rst
 - echo "Using flake8 to check Python code"
 - flake8 flake8_rst_docstrings.py

install:
 - python setup.py install

script:
 - echo "On this machine \$LANG=$LANG"
 - echo "Checking our own docstrings are valid RST"
 - flake8 --select RST flake8_rst_docstrings.py
 - echo "Checking we can parse our valid test cases"
 - flake8 --select RST tests/test_cases/*.py

notifications:
  email: false
